#############################################################################
# Makefile for building: nonogram-qt
# Generated by qmake (2.01a) (Qt 4.8.7) on: jeu. déc. 10 15:37:01 2020
# Project:  nonogram-qt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile nonogram-qt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cluenumberbutton.cpp \
		flowlayout.cpp \
		linesolver.cpp \
		main.cpp \
		mainmenu.cpp \
		nonogram.cpp \
		nonogramexport.cpp \
		pushbutton.cpp \
		puzzlecreator.cpp \
		puzzlegame.cpp \
		puzzlegenerator.cpp \
		puzzlelibrary.cpp \
		solver.cpp \
		tile.cpp moc_cluenumberbutton.cpp \
		moc_mainmenu.cpp \
		moc_pushbutton.cpp \
		moc_puzzlecreator.cpp \
		moc_puzzlegame.cpp \
		moc_puzzlegenerator.cpp \
		moc_puzzlelibrary.cpp \
		moc_tile.cpp
OBJECTS       = cluenumberbutton.o \
		flowlayout.o \
		linesolver.o \
		main.o \
		mainmenu.o \
		nonogram.o \
		nonogramexport.o \
		pushbutton.o \
		puzzlecreator.o \
		puzzlegame.o \
		puzzlegenerator.o \
		puzzlelibrary.o \
		solver.o \
		tile.o \
		moc_cluenumberbutton.o \
		moc_mainmenu.o \
		moc_pushbutton.o \
		moc_puzzlecreator.o \
		moc_puzzlegame.o \
		moc_puzzlegenerator.o \
		moc_puzzlelibrary.o \
		moc_tile.o
DIST          = translations/nonogram_cs.qm \
		translations/nonogram_cs.ts \
		translations/nonogram_fi.qm \
		translations/nonogram_fi.ts \
		translations/nonogram_sv.qm \
		translations/nonogram_sv.ts \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		nonogram-qt.pro
QMAKE_TARGET  = nonogram-qt
DESTDIR       = 
TARGET        = nonogram-qt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainmenu.h ui_puzzlecreator.h ui_puzzlegame.h ui_puzzlegenerator.h ui_puzzlelibrary.h ui_tile.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nonogram-qt.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile nonogram-qt.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile nonogram-qt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nonogram-qt1.0.0 || $(MKDIR) .tmp/nonogram-qt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nonogram-qt1.0.0/ && $(COPY_FILE) --parents cluenumberbutton.h flowlayout.h linesolver.h mainmenu.h nonogram.h nonogramexport.h pushbutton.h puzzlecreator.h puzzlegame.h puzzlegenerator.h puzzlelibrary.h solver.h tile.h .tmp/nonogram-qt1.0.0/ && $(COPY_FILE) --parents cluenumberbutton.cpp flowlayout.cpp linesolver.cpp main.cpp mainmenu.cpp nonogram.cpp nonogramexport.cpp pushbutton.cpp puzzlecreator.cpp puzzlegame.cpp puzzlegenerator.cpp puzzlelibrary.cpp solver.cpp tile.cpp .tmp/nonogram-qt1.0.0/ && $(COPY_FILE) --parents mainmenu.ui puzzlecreator.ui puzzlegame.ui puzzlegenerator.ui puzzlelibrary.ui tile.ui .tmp/nonogram-qt1.0.0/ && (cd `dirname .tmp/nonogram-qt1.0.0` && $(TAR) nonogram-qt1.0.0.tar nonogram-qt1.0.0 && $(COMPRESS) nonogram-qt1.0.0.tar) && $(MOVE) `dirname .tmp/nonogram-qt1.0.0`/nonogram-qt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nonogram-qt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cluenumberbutton.cpp moc_mainmenu.cpp moc_pushbutton.cpp moc_puzzlecreator.cpp moc_puzzlegame.cpp moc_puzzlegenerator.cpp moc_puzzlelibrary.cpp moc_tile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cluenumberbutton.cpp moc_mainmenu.cpp moc_pushbutton.cpp moc_puzzlecreator.cpp moc_puzzlegame.cpp moc_puzzlegenerator.cpp moc_puzzlelibrary.cpp moc_tile.cpp
moc_cluenumberbutton.cpp: cluenumberbutton.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) cluenumberbutton.h -o moc_cluenumberbutton.cpp

moc_mainmenu.cpp: puzzlegenerator.h \
		cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		puzzlecreator.h \
		nonogramexport.h \
		puzzlelibrary.h \
		puzzlegame.h \
		flowlayout.h \
		tile.h \
		mainmenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainmenu.h -o moc_mainmenu.cpp

moc_pushbutton.cpp: pushbutton.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) pushbutton.h -o moc_pushbutton.cpp

moc_puzzlecreator.cpp: pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		nonogramexport.h \
		puzzlecreator.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) puzzlecreator.h -o moc_puzzlecreator.cpp

moc_puzzlegame.cpp: cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		puzzlegame.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) puzzlegame.h -o moc_puzzlegame.cpp

moc_puzzlegenerator.cpp: cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		puzzlegenerator.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) puzzlegenerator.h -o moc_puzzlegenerator.cpp

moc_puzzlelibrary.cpp: nonogram.h \
		solver.h \
		linesolver.h \
		nonogramexport.h \
		puzzlegame.h \
		cluenumberbutton.h \
		pushbutton.h \
		flowlayout.h \
		tile.h \
		puzzlelibrary.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) puzzlelibrary.h -o moc_puzzlelibrary.cpp

moc_tile.cpp: tile.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) tile.h -o moc_tile.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainmenu.h ui_puzzlecreator.h ui_puzzlegame.h ui_puzzlegenerator.h ui_puzzlelibrary.h ui_tile.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainmenu.h ui_puzzlecreator.h ui_puzzlegame.h ui_puzzlegenerator.h ui_puzzlelibrary.h ui_tile.h
ui_mainmenu.h: mainmenu.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainmenu.ui -o ui_mainmenu.h

ui_puzzlecreator.h: puzzlecreator.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic puzzlecreator.ui -o ui_puzzlecreator.h

ui_puzzlegame.h: puzzlegame.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic puzzlegame.ui -o ui_puzzlegame.h

ui_puzzlegenerator.h: puzzlegenerator.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic puzzlegenerator.ui -o ui_puzzlegenerator.h

ui_puzzlelibrary.h: puzzlelibrary.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic puzzlelibrary.ui -o ui_puzzlelibrary.h

ui_tile.h: tile.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic tile.ui -o ui_tile.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

cluenumberbutton.o: cluenumberbutton.cpp cluenumberbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cluenumberbutton.o cluenumberbutton.cpp

flowlayout.o: flowlayout.cpp flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowlayout.o flowlayout.cpp

linesolver.o: linesolver.cpp linesolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesolver.o linesolver.cpp

main.o: main.cpp mainmenu.h \
		puzzlegenerator.h \
		cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		puzzlecreator.h \
		nonogramexport.h \
		puzzlelibrary.h \
		puzzlegame.h \
		flowlayout.h \
		tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainmenu.o: mainmenu.cpp mainmenu.h \
		puzzlegenerator.h \
		cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		puzzlecreator.h \
		nonogramexport.h \
		puzzlelibrary.h \
		puzzlegame.h \
		flowlayout.h \
		tile.h \
		ui_mainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainmenu.o mainmenu.cpp

nonogram.o: nonogram.cpp nonogram.h \
		solver.h \
		linesolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nonogram.o nonogram.cpp

nonogramexport.o: nonogramexport.cpp nonogramexport.h \
		nonogram.h \
		solver.h \
		linesolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nonogramexport.o nonogramexport.cpp

pushbutton.o: pushbutton.cpp pushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pushbutton.o pushbutton.cpp

puzzlecreator.o: puzzlecreator.cpp puzzlecreator.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		nonogramexport.h \
		ui_puzzlecreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzlecreator.o puzzlecreator.cpp

puzzlegame.o: puzzlegame.cpp puzzlegame.h \
		cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		ui_puzzlegame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzlegame.o puzzlegame.cpp

puzzlegenerator.o: puzzlegenerator.cpp puzzlegenerator.h \
		cluenumberbutton.h \
		pushbutton.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		ui_puzzlegenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzlegenerator.o puzzlegenerator.cpp

puzzlelibrary.o: puzzlelibrary.cpp puzzlelibrary.h \
		nonogram.h \
		solver.h \
		linesolver.h \
		nonogramexport.h \
		puzzlegame.h \
		cluenumberbutton.h \
		pushbutton.h \
		flowlayout.h \
		tile.h \
		ui_puzzlelibrary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzlelibrary.o puzzlelibrary.cpp

solver.o: solver.cpp solver.h \
		linesolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solver.o solver.cpp

tile.o: tile.cpp tile.h \
		ui_tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tile.o tile.cpp

moc_cluenumberbutton.o: moc_cluenumberbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cluenumberbutton.o moc_cluenumberbutton.cpp

moc_mainmenu.o: moc_mainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainmenu.o moc_mainmenu.cpp

moc_pushbutton.o: moc_pushbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pushbutton.o moc_pushbutton.cpp

moc_puzzlecreator.o: moc_puzzlecreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_puzzlecreator.o moc_puzzlecreator.cpp

moc_puzzlegame.o: moc_puzzlegame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_puzzlegame.o moc_puzzlegame.cpp

moc_puzzlegenerator.o: moc_puzzlegenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_puzzlegenerator.o moc_puzzlegenerator.cpp

moc_puzzlelibrary.o: moc_puzzlelibrary.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_puzzlelibrary.o moc_puzzlelibrary.cpp

moc_tile.o: moc_tile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tile.o moc_tile.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/nonogram-qt/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/nonogram-qt/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/nonogram-qt/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/nonogram-qt/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/nonogram-qt/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/nonogram-qt/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

